name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-bot:
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cleanup
        run: brew test-bot --only-cleanup-before

      - name: Setup
        run: brew test-bot --only-setup

      - name: Tap syntax
        run: brew test-bot --only-tap-syntax
