name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test tap
        run: brew test-bot --only-cleanup-before --only-setup --only-tap-syntax
